config/routes.rb
Rails.application.routes.draw do
  resources :stations
  resources :routes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #get 'api/v1/stations'=>'stations#stationsXroutes'

  namespace :api, defaults:{ format: :json } do
    namespace :v1 do
      get     "/stations",     to: "api_stations#stationsXroutes"
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/route.rb
class Route < ApplicationRecord
  has_many:stations
  belongs_to  :stationsroute
end

app/models/ruta.rb
class Ruta < ApplicationRecord
  #has_many:stationsroutes
  #has_many:stations, :through => :stationsroutes
end

app/models/station.rb
class Station < ApplicationRecord
  #belongs_to :route
  include ActiveModel::AttributeAssignment
  attr_accessor :routes

  has_many:stationsroutes
  has_many:route, :through => :stationsroutes

end

app/models/stationsroute.rb
class Stationsroute < ApplicationRecord
  belongs_to  :route
  belongs_to  :station
end

app/controllers/api/v1/api_stations_controller.rb
class Api::V1::ApiStationsController < ApplicationController

  # Test function API

  def stationsXroutes
    @stations = Station.all


    @result = Array.new

    @stations.each do |station|
      @stations_routes_list = Stationsroute.select("nomRuta").joins(:route).joins(:station).where({station_id: station.id})
      @result << {
          cod: station.id,
          nombre: station.nomParada,
          latitud:station.latParada,
          longitud:station.lonParada,
          rutas: @stations_routes_list,
      }
    end

    respond_to do |format|
      format.json { render json: @result }
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:codRuta, :nomRuta, :numBuses, :observRuta)
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: [:show, :edit, :update, :destroy]
  before_action :prepare_route_list, only: [:new, :edit]
  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
    @stations.each do |station|
      @stations_routes_list = Stationsroute.select("nomRuta").joins(:route).joins(:station).where({station_id: station.id})
    end

  end

  # GET /stations/1
  # GET /stations/1.json
  def show
   @stations_routes_list = Stationsroute.select("nomRuta").joins(:route).joins(:station).where({station_id: @station.id})

  end

  # GET /stations/new
  def new
    @station = Station.new

    @all_routes = Route.all
    @stations_routes = @station.stationsroutes.build
  end

  # GET /stations/1/edit
  def edit
    @all_routes = Route.all
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)
    params[:routes][:ids].each do |route|
      if !route.empty?
        @station.stationsroutes.build(:route_id => route)
        #Station.attribute(:routes => "test")
      end
    end


    respond_to do |format|
      if @station.save
        format.html {redirect_to @station, notice: 'Station was successfully created.'}
        format.json {render :show, status: :created, location: @station}
      else
        format.html {render :new}
        format.json {render json: @station.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update

    params[:route][:id].each do |route|
      if !route.empty?
        @station.stationsroutes.build(:route_id => route)
      end
    end

    respond_to do |format|
      if @station.update(station_params)
        format.html {redirect_to @station, notice: 'Station was successfully updated.'}
        format.json {render :show, status: :ok, location: @station}
      else
        format.html {render :edit}
        format.json {render json: @station.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html {redirect_to stations_url, notice: 'Station was successfully destroyed.'}
      format.json {head :no_content}
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_station
    @station = Station.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def station_params
    params.require(:station).permit(:codParada, :nomParada, :latParada, :lonParada, :route_id, :routes)
  end

  def prepare_route_list
    @routes = Route.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TransappApiMysql</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/routes/_form.html.erb
<%= form_with(model: route, local: true) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codRuta %>
    <%= form.text_field :codRuta, id: :route_codRuta %>
  </div>

  <div class="field">
    <%= form.label :nomRuta %>
    <%= form.text_field :nomRuta, id: :route_nomRuta %>
  </div>

  <div class="field">
    <%= form.label :numBuses %>
    <%= form.number_field :numBuses, id: :route_numBuses %>
  </div>

  <div class="field">
    <%= form.label :observRuta %>
    <%= form.text_field :observRuta, id: :route_observRuta %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Codruta</th>
      <th>Nomruta</th>
      <th>Numbuses</th>
      <th>Observruta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.codRuta %></td>
        <td><%= route.nomRuta %></td>
        <td><%= route.numBuses %></td>
        <td><%= route.observRuta %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codruta:</strong>
  <%= @route.codRuta %>
</p>

<p>
  <strong>Nomruta:</strong>
  <%= @route.nomRuta %>
</p>

<p>
  <strong>Numbuses:</strong>
  <%= @route.numBuses %>
</p>

<p>
  <strong>Observruta:</strong>
  <%= @route.observRuta %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

app/views/stations/_form.html.erb
<%= form_with(model: station, local: true) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codParada %>
    <%= form.text_field :codParada, id: :station_codParada %>
  </div>

  <div class="field">
    <%= form.label :nomParada %>
    <%= form.text_field :nomParada, id: :station_nomParada %>
  </div>

  <div class="field">
    <%= form.label :latParada %>
    <%= form.text_field :latParada, id: :station_latParada %>
  </div>

  <div class="field">
    <%= form.label :lonParada %>
    <%= form.text_field :lonParada, id: :station_lonParada %>
  </div>

    <div class="field">
          <%= collection_select(:routes, :ids, @all_routes, :id, :nomRuta, {}, {:multiple => true}) %>
        </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stations</h1>

<table>
  <thead>
    <tr>
      <th>Codparada</th>
      <th>Nomparada</th>
      <th>Latparada</th>
      <th>Lonparada</th>
      <th>Route</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stations.each do |station| %>
      <tr>
        <td><%= station.codParada %></td>
        <td><%= station.nomParada %></td>
        <td><%= station.latParada %></td>
        <td><%= station.lonParada %></td>
        <td><%= collection_select(:route, :id,  @stations_routes_list, :id, :nomRuta, {}, {:multiple => true}) %></td>
        <td><%= link_to 'Show', station %></td>
        <td><%= link_to 'Edit', edit_station_path(station) %></td>
        <td><%= link_to 'Destroy', station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codparada:</strong>
  <%= @station.codParada %>
</p>

<p>
  <strong>Nomparada:</strong>
  <%= @station.nomParada %>
</p>

<p>
  <strong>Latparada:</strong>
  <%= @station.latParada %>
</p>

<p>
  <strong>Lonparada:</strong>
  <%= @station.lonParada %>
</p>


<p>
  <strong>Rutas</strong>
  <%= @station.routes %>
</p>

<p>
  <strong>Rutas:</strong>
  <%= collection_select(:routes, :id,  @stations_routes_list, :id, :nomRuta, {}, {:multiple => true}) %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>